joint_poses:
  - [0.0006, -0.2015, 0.0004, -2.4342, -0.0007, 2.2264, 0.7006]
  - [-0.2242, -0.1941, -0.0004, -2.4248, 0.2798, 2.1494, 0.3110]
  - [-0.2036, 0.0488, -0.0005, -2.1111, 0.1966, 1.8663, 0.4368]
  - [-0.1926, 0.0963, -0.0005, -1.8820, 0.0664, 1.6410, 0.1097]
  - [-0.2909, 0.1112, -0.0006, -1.8830, 0.3128, 1.6097, 0.0730]
  - [0.0472, 0.3889, -0.0003, -1.6271, -0.1271, 1.5848, 0.8354]
  - [0.0645, -0.6634, -0.0004, -2.8831, -0.3008, 2.4019, 1.0995]
  - [0.5045, -0.4670, -0.0005, -2.7064, -0.5707, 2.1512, 1.6476]
  - [0.3695, 0.2195, -0.0003, -1.8866, -0.2824, 1.6852, 1.1573]
  - [0.0008, -0.0741, -0.0002, -2.0800, -0.0017, 2.0004, 0.1122]
  - [0.1112, 0.2668, 0.0004, -1.6255, -0.2919, 1.5170, 0.2046]
  - [-0.5302, -0.4274, -0.0081, -2.4483, 0.5672, 1.7416, -0.4738]
