joint_poses:
  - [0.0007, -0.2027, 0.0008, -2.4339, -0.0007, 2.2272, 0.7005]
  - [-0.2244, -0.1948, -0.0006, -2.4230, 0.2809, 2.1488, 0.3104]
  - [-0.2036, 0.0480, -0.0007, -2.1093, 0.1959, 1.8657, 0.4372]
  - [-0.1926, 0.0955, -0.0008, -1.8800, 0.0656, 1.6404, 0.1090]
  - [-0.2912, 0.1105, -0.0007, -1.8820, 0.3138, 1.6090, 0.0722]
  - [0.0474, 0.3880, -0.0002, -1.6252, -0.1281, 1.5839, 0.8360]
  - [0.0649, -0.6641, -0.0006, -2.8827, -0.3020, 2.4027, 1.1002]
  - [0.5047, -0.4673, -0.0004, -2.7046, -0.5718, 2.1506, 1.6483]
  - [0.3691, 0.2188, -0.0002, -1.8849, -0.2816, 1.6845, 1.1568]
  - [0.0004, -0.0754, -0.0000, -2.0794, -0.0008, 2.0013, 0.1115]
  - [0.1112, 0.2660, 0.0006, -1.6236, -0.2928, 1.5165, 0.2051]
  - [-0.5306, -0.4283, -0.0087, -2.4478, 0.5683, 1.7424, -0.4746]
